name: json_placeholder
description: "Json Placeholder"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  get_it: ^7.6.7
  http: ^1.2.1
  injectable: ^2.3.2
  flutter_bloc: ^8.1.4
  sqflite: ^2.3.2
  path: ^1.9.0
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  golden_toolkit: ^0.15.0
  injectable_generator: ^2.4.1
  mockito: ^5.4.4
  test: ^1.24.9 # Not possible to upgrade yet

flutter:

  uses-material-design: true
